## Pre-commit Workflow
# Last update: 2024-05-27

# Save this file to './.github/workflows/pre-commit-workflow.yaml'

# Name of the workflow
name: pre-commit

# Controls on when the workflow will run
on:
  pull_request:

  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job name
  pre-commit:
    # Type of machine to run the job on
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository content - https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK - https://github.com/actions/setup-dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.x' # Latest stable major version of .NET Core SDK

      - name: Install .NET dependencies
        run: |
          dotnet restore

      - name: Build the project
        run: |
          dotnet build --configuration Release

      - name: Run tests
        run: |
          dotnet test --configuration Release
